# Generated by Django 5.1.1 on 2024-09-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_task_category_task_recurrence_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(default=8825777232, max_length=10),
            preserve_default=False,
        ),
    ]
