# Generated by Django 5.1.1 on 2024-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_google_token_expiry_profile_google_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
